[tox]
envlist = py314, lint, type
isolated_build = true

[testenv]
deps =
    pytest
    pytest-qt
commands =
    pytest {posargs:tests}

[testenv:lint]
description = Run Ruff checks
skip_install = true
deps =
    ruff
commands =
    ruff check .

[testenv:type]
description = Run Pyright
deps =
    basedpyright
    pytest
commands =
    basedpyright --pythonpath {envpython} src tests
