from typing import Protocol, runtime_checkable

from .geometry import Vector3
from .waveform import Waveform

__all__ = [
    "LaserAdapter",
    "PowerMeterAdapter",
    "ScopeAdapter",
    "StageAdapter",
]


@runtime_checkable
class ScopeAdapter(Protocol):
    def identify(self) -> str: ...
    def configure(self) -> None: ...
    def get_channels(self) -> list[str]: ...
    def set_average_count(self, average_count: int) -> None: ...
    def acquire(self) -> None: ...
    def read_waveform(self, channel: str) -> Waveform: ...


@runtime_checkable
class LaserAdapter(Protocol):
    def identify(self) -> str: ...
    def configure(self) -> None: ...
    def get_output(self) -> bool: ...
    def set_output(self, enabled: bool) -> None: ...
    def get_frequency(self) -> float: ...
    def set_frequency(self, frequency: float) -> None: ...
    def get_tune(self) -> float: ...
    def set_tune(self, tune: float) -> None: ...
    def get_head_temperature(self) -> float: ...
    def get_diode_temperature(self) -> bool: ...


@runtime_checkable
class StageAdapter(Protocol):
    def identify(self) -> str: ...
    def configure(self) -> None: ...
    def get_position(self) -> Vector3: ...
    def is_moving(self) -> bool: ...
    def move_relative(self, offset: Vector3) -> None: ...
    def move_absolute(self, position: Vector3) -> None: ...


@runtime_checkable
class PowerMeterAdapter(Protocol):
    def identify(self) -> str: ...
    def configure(self) -> None: ...
    def get_wavelength(self) -> float: ...
    def set_wavelength(self, wavelength: float) -> None: ...
    def get_average_count(self) -> int: ...
    def set_average_count(self, average_count: int) -> None: ...
    def measure_power(self) -> float: ...
